"""area size

Revision ID: 16ce392d025f
Revises: de3fce11bbcf
Create Date: 2021-06-02 09:28:19.380133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ce392d025f'
down_revision = 'de3fce11bbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('size', sa.Float(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'size')
    # ### end Alembic commands ###
