"""per-area observations

Revision ID: 69f7cc9e28fe
Revises: 97bf9352ebcc
Create Date: 2021-05-08 13:37:20.957201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f7cc9e28fe'
down_revision = '97bf9352ebcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('area_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'observation', 'area', ['area_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_column('observation', 'area_name')
    # ### end Alembic commands ###
