"""initial schema

Revision ID: 97bf9352ebcc
Revises: 
Create Date: 2021-04-24 11:56:16.278915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bf9352ebcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('observation',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('variable', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'dataset', 'variable')
    )
    op.create_table('watering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['area_name'], ['area.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering')
    op.drop_table('observation')
    op.drop_table('area')
    # ### end Alembic commands ###
