"""better obs constraint

Revision ID: de3fce11bbcf
Revises: fba9da49180d
Create Date: 2021-05-15 11:08:39.036293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3fce11bbcf'
down_revision = 'fba9da49180d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('observation_timestamp_dataset_variable_key', 'observation', type_='unique')
    op.create_unique_constraint(None, 'observation', ['timestamp', 'dataset', 'variable', 'area_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observation', type_='unique')
    op.create_unique_constraint('observation_timestamp_dataset_variable_key', 'observation', ['timestamp', 'dataset', 'variable'])
    # ### end Alembic commands ###
