"""water levels

Revision ID: f0ccf576d3fc
Revises: 69f7cc9e28fe
Create Date: 2021-05-08 13:41:07.645062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ccf576d3fc'
down_revision = '69f7cc9e28fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_level',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('area_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['area_name'], ['area.name'], ),
    sa.PrimaryKeyConstraint('timestamp', 'area_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_level')
    # ### end Alembic commands ###
